- entrypoint/entrypoint.go
- errors/errors.go
- logging/logging.go
This PR does the following:
1. A few tweaks to the default log settings, including enabling timestamps and showing stack traces.
1. Add a helper method to catch panics in the CLI and still show stack traces for those.
> Improve logging. Add panic handling for CLI.

- shell/cmd.go
Implementation is borrowed from Terratest.
> Add shell command to capture and stream output

- README.md
- circle.yml
- glide.lock
- glide.yaml
- logging/logging.go
- shell/options.go
[logrus](https://github.com/sirupsen/logrus) changed their GitHub repo to all lowercase and broke all go packages that use their library.
See [here](https://github.com/sirupsen/logrus/issues/553) and [here](https://github.com/sirupsen/logrus)
> fix issue with logrus capitalization

- shell/prompt.go
- shell/prompt_test.go
This refactors the prompt functions to take in `io.Writer` and `io.Reader` so that they are testable. Also adds a bunch of unit tests for the two functions (`speakeasy` doesn't appear to be testable) as a part of that.
> Unit tests for shell prompt functions

- README.md
- entrypoint/entrypoint.go
- entrypoint/entrypoint_test.go
- entrypoint/help_utils.go
- entrypoint/help_utils_test.go
This adds the wrapped help text printer to `gruntwork-cli` and a function to create a new `cli.App` that takes advantage of it.
Original
```
NAME:
houston - A CLI tool for interacting with Gruntwork Houston that you can use to authenticate to AWS on the CLI and to SSH to your EC2 Instances.
USAGE:
houston [global options] command [command options] [arguments...]
VERSION:
snapshot
COMMANDS:
exec       Execute a command with temporary AWS credentials obtained by logging into Gruntwork Houston
ssh        Connect to an EC2 instance via SSH with your public key.
configure  Configure houston CLI options.
profiles   Show a status of all the defined profiles.
start      Start the background HTTP server process so it can cache your AWS credentials. Note: the exec command starts the HTTP server …
```
> Wrapper around help text

- url/url.go
- url/url_test.go
My entire life is spent creating libraries for properly manipulating URLs.
> Add URL helpers

- shell/cmd.go
- shell/cmd_test.go
- shell/options.go
Right now we log the command string when we call commands using `RunShellCommand`, which is really nice for debugging purposes. However, sometimes this should be suppressed because the args might include sensitive data. For example, when scripting calls to `openssl` to create certs, the password can only be passed in via the command line when avoiding the prompt.
The solution proposed and implemented here is to add a new shell option that marks the commands as having sensitive args, which is used to suppress logging the args.
> Add concept of sensitive args

- entrypoint/entrypoint.go
- errors/errors.go
The stack traces are very useful, but as a customer facing CLI, it can be rather verbose and is useless unless they know the source code.
This introduces the concept of a debug mode for configuring when to print out the stack trace. Now the command will only print out stack traces when run with `GRUNTWORK_DEBUG=1`.
Note: I couldn't find a good way to unit test this, given that `checkForErrorsAndExit` kills the process. For now, here is the manual test demo:
Without env:
```
%~> go run main.go                                                                                                                                        [0]
ERRO[2018-11-28T11:31:10-08:00] --aws-region is required                      error="--aws-region is required"
exit status 1
```
With env:
```
%~> …
```
> Configurable stack traces

- entrypoint/assertions.go
- entrypoint/assertions_test.go
- `StringFlagRequiredE`: Assert that a string flag is passed in ([urfave does not support this natively yet](https://github.com/urfave/cli/issues/85))
- `EnvironmentVarRequiredE`: Assert that a certain environment variable is defined.
> Add functions to make certain assertions

- entrypoint/entrypoint.go
If we have nested commands (e.g `kubergrunt eks configure`), then the help text for the second level is still using the default `urfave` template. This updates it to use the same one as the app level:
Original:
```
NAME:
kubergrunt eks - Helper commands to configure EKS, including setting up operator machines to authenticate with EKS.
USAGE:
kubergrunt eks command [command options] [arguments...]
COMMANDS:
configure  Set up kubectl to be able to authenticate with EKS.
token      Get token for Kubernetes using AWS IAM credential.
OPTIONS:
--help, -h  show help
```
Updated:
```
Usage: kubergrunt eks [--help] command [options] [args]
Helper commands to configure EKS, including setting up operator machines to authenticate with EKS.
Commands:
configure  Set up kubectl to be able to …
```
> Use the same format for nested commands

- collections/lists.go
- collections/lists_test.go
This implements `BatchListIntoGroupsOf`, which will take a list of strings and batch them into groups of `batchSize`.
> Add BatchListIntoGroupsOf

- shell/cmd.go
- shell/cmd_test.go
- shell/options.go
Currently the `shell` module does not support custom environment variables when running commands. This PR adds a new `Env` option to the `ShellOptions` struct which will be converted to environment variables for the `Cmd` struct.
> Support custom environment variables when running commands via the shell module

- random/random.go
- random/random_test.go
In the GCP bootstrap script I am currently developing, I have a need to generate a random string that I can use as a unique identifier for seeding the Project ID when creating a new project. I haven't seen us provide this as a library outside of `terratest`, so I ported a version of `random.UniqueId` here that is more generic, where you can control char sets and digits.
Note that this uses `crypto/rand` instead of `math/rand`, to allow for potential usage with password generation.
> Add random string generation capabilities

- entrypoint/entrypoint.go
- entrypoint/entrypoint_test.go
- errors/errors.go
I noticed that the user experience for returning `ErrorWithExitCode` isn't quite great, so I made a few improvements here:
- Support using both `WithStackTrace` and `ErrorWithExitCode`, so that you can get both a stack trace and exit with exit code.
- Output the underlying error message instead of `ErrorWithExitCode{ Err = Deployment failed, ExitCode = 1 }`
- Refactor `checkForErrorsAndExit` so we can test the exit code functionality without the test exiting due to the call to `os.Exit`.
> Improve ErrorWithExitCode

- logging/formatter.go
- logging/logging.go
Gives you logs that look like below:
```
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]   ami-builder
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]       build-packer-artifact
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]   docker-image-builder
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]       build-docker-image
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]   terraform-applier
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]       infrastructure-deploy-script
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]       terraform-update-variable
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]   terraform-planner
[infrastructure-deployer] INFO[2020-08-19T11:23:08-05:00]       infrastructure-deploy-script
```
> Introduce a log text formatter that prefixes the binary name to the log entry

- README.md
- entrypoint/help_utils.go
- entrypoint/help_utils_test.go
- version/version.go
I would want to add only one package `version`. To be honest I don't like keep VERSION in main.go.
Reasons:
1. VERSION - uppercase 
2. This forces to always add an excess arg `cli.NewApp(VERSION)`
It's easy to make DevOps compatible with both implementations. Just try to rewrite in both places:
`-ldflags "-X main.VERSION=v1.0.0 -X github.com/gruntwork-io/gruntwork-cli/version.VERSION=v1.0.0"`
> Add version package

- shell/cmd.go
- shell/cmd_test.go
- shell/test-fixture/echo_hi_stderr.sh
This adds `RunCommandAndGetStdout` flavors of `RunCommand`. I could probably do a better job with refactoring to make things DRY, but I don't have enough of an appetite right now to clean things up as this is blocking the architecture catalog automation work.
> Add GetStdout flavors

- README.md
- entrypoint/entrypoint.go
- entrypoint/entrypoint_test.go
- files/files.go
- files/paths.go
- go.mod
- shell/cmd.go
- shell/cmd_test.go
- shell/options.go
- shell/prompt.go
- url/url.go
- version/version.go
This PR renames the references to `gruntwork-cli` to `go-commons`.
> Rename to go-commons

- README.md
This repo was still pointing to godoc badge, which is now deprecated and replaced by pkg.go.dev, so this PR updates the docs link to use pkg.go.dev.
I also pulled the relevant go badges from terratest (goreportcard and go mod version).
> Add relevant go badges

- README.md
- entrypoint/assertions.go
- entrypoint/assertions_test.go
- entrypoint/entrypoint.go
- entrypoint/entrypoint_test.go
- entrypoint/help_utils.go
- errors/errors.go
- go.mod
- go.sum
This bumps `urfave/cli` to v2 track. This is an opportunistic upgrade (we're not using any of the features yet) so that we can stay up to date as bugs are fixed.
> Bump urfave/cli to v2

- git/auth.go
- git/git.go
- git/git_test.go
- git/test/auth_test.go
Sometimes, for security reasons, we may want to suppress the log output of the git commands running. This is not possible with the current functions, as it uses the default logger associated with the `ShellOptions`.
This PR updates the functions in the `git` module to accept the logger object explicitly, and configure it if non-nil.
This PR is backward **incompatible**.
The functions in the `git` module has been updated to require a `logrus.Logger` object to be passed in to use as the logger for the git commands. You can pass in `nil` for the new arg to retain the old behavior.
> Add the ability to configure logger for git functions

- git/test/auth_test.go
- lock/lock.go
This PR updates the `lock` library to support using an already configured/authd AWS session. The use case for this is in the `refarch-deployer` utility, where all the authentication is handled internally based on where you are running, and more specifically, the local case where we use `aws-vault` as a library to auth to the different accounts, so the default credential chain is empty.
> Add ability to provide an authentication session to lock

- git/auth.go
- git/test/auth_test.go
This PR adds two new functions `git.ConfigureCacheCredentialsHelper` and `git.StoreCacheCredentials`. These functions give the CLI more control over the credential caching behavior of git, allowing you to have mixed credentials for accessing different repos.
This is most useful when you are using GitHub Apps for repo access, which can only auth to a single org at a time. In such situation, you need the ability to provide different credentials for different orgs.
> Expose underlying git config calls as functions to further customize credential cache

- collections/doc.go
- entrypoint/doc.go
- errors/doc.go
- files/doc.go
- lock/doc.go
- logging/doc.go
- random/doc.go
- random/random.go
- retry/doc.go
- shell/doc.go
- shell/output.go
- ssh/doc.go
- ssh/ssh.go
- url/doc.go
- url/url.go
- version/doc.go
This PR sets package level documentation for all the modules in `go-commons` so that they show up in [the pkg.go.dev list](https://pkg.go.dev/github.com/gruntwork-io/go-commons#section-directories).
> Cleanup package docs so they show up in pkg.go.dev

- collections/maps.go
- collections/maps_test.go
This PR introduces a Go Map Flatten function which is useful for turning a map of type `map[string]string` into a string slice of `key=value` items.
> Add a map flatten function

- .circleci/config.yml
- github/auth.go
- github/auth_test.go
- go.mod
- go.sum
This adds a new package `github` that contains functions for interacting with GitHub. To start, this contains functions that are useful for authenticating as Github App, which is becoming increasingly common with our Lambda based services (`refarch-deployer-runner`, `discussion-labeler`, and soon `release-notes-drafter`). Once this is released, I'll start updating each of these to use this central implementation.
> Add new utility functions for authenticating as a Github App

- github/auth.go
Fixes a bug in the new `github` package to properly handle the json unmarshal. It turns out using a nil uninitialized pointer is not supported (leads to the following runtime error):
```
Error loading configured Github App Config JSON: json: Unmarshal(nil *github.GithubAppConfig)
```
> Must have struct for json to work, not nil

- collections/maps.go
- collections/maps_test.go
This adds a new function that helps with converting a key=value slice of strings to a map. This is useful for working with the return value of `os.Environ()`.
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).
- Added a new function `collections.KeyValueStringSliceAsMap` which can be used to work with a slice of `key=value` pairs.
> Add function to convert key=value slice pairs to map

- awscommons/v2/autoscaling.go
- awscommons/v2/autoscaling_test.go
- awscommons/v2/errors.go
- go.mod
- go.sum
- logging/logging.go
Utility functions for autoscaling.
Relates to https://github.com/gruntwork-io/ecsgrunt/pull/2.
> Add utilities for autoscaling.

- files/paths.go
- files/paths_test.go
Original bug fix: https://github.com/gruntwork-io/terragrunt/pull/100
Part of #75.
> Port a bug fix for GetPathRelativeTo over from Terragrunt

- files/paths.go
- files/paths_test.go
Related to #75.
Without this change the relative paths are not computed correctly in case when `basePath` is a subfolder of `path`, and one  of them is a symbolic link of the other.
Note that I had to create fixtures for test cases of `GetPathRelativeTo()`, because the `filepath.EvalSymlinks()` method that we're now using is actually looking for files on disk.
> Make GetPathRelativeTo() resolve symbolic links

- collections/lists.go
No need to use `comparable` type for _BatchListIntoGroupsOf_ func. It restricts the use of this function to other types of slices.
> Fix input var type for BatchListIntoGroupsOf

- README.md
- collections/maps.go
- collections/maps_test.go
- env/env.go
- env/env_test.go
- errors/errors.go
Extend the shared libraries from the terragrunt repository https://github.com/gruntwork-io/terragrunt/tree/master/pkg
> feat: extend the shared libraries

- .circleci/config.yml
[CI for this repo](https://app.circleci.com/pipelines/github/gruntwork-io/go-commons/262/workflows/f2b4d31e-afef-4ff6-8a3c-5a25440c55c6/jobs/447) is broken, following recommended remediation:
> Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running
> remove docker image specification
